export const inspectionErrorCodes = [
  "AUTHORIZATION_CODE_MISMATCH",
  "EFFECTIVE_DATE_MISMATCH",
  "EXPIRY_DATE_MISMATCH",
  "REGION_MISMATCH",
  "AUTHORIZATION_TYPE_MISMATCH",
  "AUTHORIZATION_LEVEL_MISMATCH",
  "GRANTOR_MISMATCH",
  "GRANTEE_MISMATCH",
  "BRAND_MISMATCH",
  "CATEGORY_MISMATCH",
  "PROJECT_MISMATCH",
  "FULL_CATEGORY_OVERCLAIM",
  "NATIONWIDE_OVERCLAIM",
  "AUTHORIZATION_CHAIN_REVIEW_REQUIRED",
  "ATTACHMENT_UNAVAILABLE",
  "ATTACHMENT_PARSE_FAILED",
  "EVIDENCE_CONFLICT",
  "LOW_CONFIDENCE_REVIEW_REQUIRED",
] as const;

export type InspectionErrorCode = (typeof inspectionErrorCodes)[number];
