import type { EvidenceReview, InspectionTask } from "./types.js";

export const demoTasks: InspectionTask[] = [
  {
    id: "task-babycare",
    brand: "BABYCARE",
    code: "26062914254888",
    name: "BABYCARE-商标注册证书",
    status: "REVIEW_REQUIRED",
    risk: "CRITICAL",
    issueCount: 2,
    assignee: "待分配",
    updatedAt: "2026-07-23 16:20",
  },
  {
    id: "task-yinbabei",
    brand: "印芭贝",
    code: "26071319475337",
    name: "印芭贝-商标注册证书",
    status: "REVIEW_REQUIRED",
    risk: "CRITICAL",
    issueCount: 2,
    assignee: "张复核",
    updatedAt: "2026-07-23 16:18",
  },
  {
    id: "task-hengjingsen",
    brand: "恒净森",
    code: "26071315192350",
    name: "恒净森-商标注册证书",
    status: "REVIEW_REQUIRED",
    risk: "CRITICAL",
    issueCount: 1,
    assignee: "李质检",
    updatedAt: "2026-07-23 16:16",
  },
  {
    id: "task-hoyo",
    brand: "HOYO",
    code: "26042212341521",
    name: "HOYO授权书",
    status: "REVIEWED",
    risk: "LOW",
    issueCount: 0,
    assignee: "王复核",
    updatedAt: "2026-07-23 16:12",
  },
];

const babycareReview: EvidenceReview = {
  taskId: "task-babycare",
  attachmentTitle: "商标注册证",
  attachmentPages: 1,
  attachmentUrl: "https://example.test/babycare.pdf",
  documentNumber: "第 48623859 号",
  documentBody: [
    "注册人：杭州白贝壳实业股份有限公司",
    "注册日期 2022年09月07日",
    "有效期至 2032年09月06日",
  ],
  overallConfidence: 0.96,
  canAutoCorrect: false,
  manualReviewReasons: ["日期字段与现存记录冲突，需人工确认后处理"],
  comparisons: [
    {
      field: "effectiveDate",
      label: "生效日期",
      sourceValue: "2032-09-07",
      attachmentValue: "2022-09-07",
      correctedValue: "2022-09-07",
      comparisonStatus: "SOURCE_FIELD_ERROR",
      action: "update",
      evidencePage: 1,
      evidenceText: "注册日期 2022年09月07日",
      confidence: 0.96,
    },
    {
      field: "expiryDate",
      label: "失效日期",
      sourceValue: "2022-09-06",
      attachmentValue: "2032-09-06",
      correctedValue: "2032-09-06",
      comparisonStatus: "SOURCE_FIELD_ERROR",
      action: "update",
      evidencePage: 1,
      evidenceText: "有效期至 2032年09月06日",
      confidence: 0.96,
    },
    {
      field: "grantor",
      label: "证书主体",
      sourceValue: "杭州白贝壳实业股份有限公司",
      attachmentValue: "杭州白贝壳实业股份有限公司",
      correctedValue: "杭州白贝壳实业股份有限公司",
      comparisonStatus: "CONSISTENT",
      action: "keep",
      evidencePage: 1,
      evidenceText: "注册人：杭州白贝壳实业股份有限公司",
      confidence: 0.98,
    },
  ],
};

const hoyoReview: EvidenceReview = {
  taskId: "task-hoyo",
  attachmentTitle: "授权书",
  attachmentPages: 1,
  attachmentUrl: "https://example.test/hoyo.pdf",
  documentNumber: "HOYO-2026-01",
  documentBody: [
    "授权方：示例品牌管理有限公司",
    "被授权方：示例供应链有限公司",
    "授权期限至 2026年12月31日止",
  ],
  overallConfidence: 0.95,
  canAutoCorrect: false,
  manualReviewReasons: ["附件未明确生效日期，保持为空并进入人工复核"],
  comparisons: [
    {
      field: "effectiveDate",
      label: "生效日期",
      sourceValue: null,
      attachmentValue: null,
      correctedValue: null,
      comparisonStatus: "ATTACHMENT_FIELD_MISSING",
      action: "review",
      evidencePage: null,
      evidenceText: "附件未明确授权开始日期",
      confidence: 0,
    },
    {
      field: "expiryDate",
      label: "失效日期",
      sourceValue: "2026-12-31",
      attachmentValue: "2026-12-31",
      correctedValue: "2026-12-31",
      comparisonStatus: "CONSISTENT",
      action: "keep",
      evidencePage: 1,
      evidenceText: "授权期限至 2026年12月31日止",
      confidence: 0.95,
    },
  ],
};

export const demoReviews: Record<string, EvidenceReview> = {
  "task-babycare": babycareReview,
  "task-yinbabei": babycareReview,
  "task-hengjingsen": babycareReview,
  "task-hoyo": hoyoReview,
};
